# Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
np.set_printoptions(precision=2, suppress=True)

# Importing Datasets

In [3]:
dataset=pd.read_csv('50_Startups.csv')

In [4]:
dataset[0:10]

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [5]:
X=dataset.iloc[:,:-1].values

In [6]:
X[0:10]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California']], dtype=object)

In [7]:
y=dataset.iloc[:,4].values

In [8]:
y[0:10]

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96])

# Encoding the Independent variable

In [9]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelEncoder=LabelEncoder()
X[:,3]=labelEncoder.fit_transform(X[:,3])
oneHotEncoder=OneHotEncoder(categorical_features=[3])
X=oneHotEncoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
X

array([[     0.  ,      0.  ,      1.  , 165349.2 , 136897.8 , 471784.1 ],
       [     1.  ,      0.  ,      0.  , 162597.7 , 151377.59, 443898.53],
       [     0.  ,      1.  ,      0.  , 153441.51, 101145.55, 407934.54],
       [     0.  ,      0.  ,      1.  , 144372.41, 118671.85, 383199.62],
       [     0.  ,      1.  ,      0.  , 142107.34,  91391.77, 366168.42],
       [     0.  ,      0.  ,      1.  , 131876.9 ,  99814.71, 362861.36],
       [     1.  ,      0.  ,      0.  , 134615.46, 147198.87, 127716.82],
       [     0.  ,      1.  ,      0.  , 130298.13, 145530.06, 323876.68],
       [     0.  ,      0.  ,      1.  , 120542.52, 148718.95, 311613.29],
       [     1.  ,      0.  ,      0.  , 123334.88, 108679.17, 304981.62],
       [     0.  ,      1.  ,      0.  , 101913.08, 110594.11, 229160.95],
       [     1.  ,      0.  ,      0.  , 100671.96,  91790.61, 249744.55],
       [     0.  ,      1.  ,      0.  ,  93863.75, 127320.38, 249839.44],
       [     1.  ,      0

## Avoiding Dummy variable trap 

In [11]:
X=X[:,1:]

In [12]:
X

array([[     0.  ,      1.  , 165349.2 , 136897.8 , 471784.1 ],
       [     0.  ,      0.  , 162597.7 , 151377.59, 443898.53],
       [     1.  ,      0.  , 153441.51, 101145.55, 407934.54],
       [     0.  ,      1.  , 144372.41, 118671.85, 383199.62],
       [     1.  ,      0.  , 142107.34,  91391.77, 366168.42],
       [     0.  ,      1.  , 131876.9 ,  99814.71, 362861.36],
       [     0.  ,      0.  , 134615.46, 147198.87, 127716.82],
       [     1.  ,      0.  , 130298.13, 145530.06, 323876.68],
       [     0.  ,      1.  , 120542.52, 148718.95, 311613.29],
       [     0.  ,      0.  , 123334.88, 108679.17, 304981.62],
       [     1.  ,      0.  , 101913.08, 110594.11, 229160.95],
       [     0.  ,      0.  , 100671.96,  91790.61, 249744.55],
       [     1.  ,      0.  ,  93863.75, 127320.38, 249839.44],
       [     0.  ,      0.  ,  91992.39, 135495.07, 252664.93],
       [     1.  ,      0.  , 119943.24, 156547.42, 256512.92],
       [     0.  ,      1.  , 114523.61,

# Splitting the dataset in training and test

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=1/3,random_state=0)

In [14]:
X_train[0:10]

array([[     0.  ,      1.  ,   1000.23, 124153.04,   1903.93],
       [     0.  ,      1.  ,    542.05,  51743.15,      0.  ],
       [     0.  ,      1.  ,  65605.48, 153032.06, 107138.38],
       [     0.  ,      1.  , 114523.61, 122616.84, 261776.23],
       [     1.  ,      0.  ,  61994.48, 115641.28,  91131.24],
       [     0.  ,      0.  ,  63408.86, 129219.61,  46085.25],
       [     0.  ,      0.  ,  78013.11, 121597.55, 264346.06],
       [     0.  ,      0.  ,  23640.93,  96189.63, 148001.11],
       [     0.  ,      0.  ,  76253.86, 113867.3 , 298664.47],
       [     0.  ,      1.  ,  15505.73, 127382.3 ,  35534.17]])

In [15]:
X_test[0:10]

array([[     1.  ,      0.  ,  66051.52, 182645.56, 118148.2 ],
       [     0.  ,      0.  , 100671.96,  91790.61, 249744.55],
       [     1.  ,      0.  , 101913.08, 110594.11, 229160.95],
       [     1.  ,      0.  ,  27892.92,  84710.77, 164470.71],
       [     1.  ,      0.  , 153441.51, 101145.55, 407934.54],
       [     0.  ,      1.  ,  72107.6 , 127864.55, 353183.81],
       [     0.  ,      1.  ,  20229.59,  65947.93, 185265.1 ],
       [     0.  ,      1.  ,  61136.38, 152701.92,  88218.23],
       [     1.  ,      0.  ,  73994.56, 122782.75, 303319.26],
       [     1.  ,      0.  , 142107.34,  91391.77, 366168.42]])

In [16]:
y_train[0:10]

array([ 64926.08,  35673.41, 101004.64, 129917.04,  99937.59,  97427.84,
       126992.93,  71498.49, 118474.03,  69758.98])

In [17]:
y_test[0:10]

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

# Fitting the model for training set

In [18]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

# Predicting the Results

In [19]:
y_pred=regressor.predict(X_test)
y_pred

array([111616.64, 132709.39, 140155.11,  76099.2 , 186329.94, 112822.2 ,
        63002.  ,  99107.1 , 119287.75, 175522.84, 101000.7 ,  85772.99,
       117713.76,  90230.88, 133375.04, 167530.55, 158013.55])

In [20]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 , 155752.6 , 132602.65])

# Backward Elimination

In [21]:
import statsmodels.api as sm
X=np.append(np.ones((50,1)).astype(int), values=X, axis = 1)
X_Opt=X[:,[0,1,2,3,4,5]]
regressorOLS=sm.OLS(endog=y , exog=X_Opt).fit()

In [22]:
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 03 Nov 2018   Prob (F-statistic):           1.34e-27
Time:                        11:37:56   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### Removing variable x2 which has highest p-value

In [23]:
X_Opt=X[:,[0,1,3,4,5]]
regressorOLS=sm.OLS(endog=y , exog=X_Opt).fit()
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sat, 03 Nov 2018   Prob (F-statistic):           8.49e-29
Time:                        11:37:56   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### Removing variable x1 

In [24]:
X_Opt=X[:,[0,3,4,5]]
regressorOLS=sm.OLS(endog=y , exog=X_Opt).fit()
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sat, 03 Nov 2018   Prob (F-statistic):           4.53e-30
Time:                        11:37:57   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [25]:
X_Opt=X[:,[0,3,5]]
regressorOLS=sm.OLS(endog=y , exog=X_Opt).fit()
regressorOLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sat, 03 Nov 2018   Prob (F-statistic):           2.16e-31
Time:                        11:37:57   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### It's upto us we can keep or remove x2 variable based on our chosen p-value